# Generated by Django 3.2.24 on 2024-04-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review2',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('message', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Review2',
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
