# Generated by Django 3.2.24 on 2024-04-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20240403_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review2',
            new_name='Review',
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
