# Generated by Django 3.2.24 on 2024-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20240403_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=45)),
                ('userEmail', models.CharField(max_length=50)),
                ('userPass', models.CharField(max_length=60)),
                ('userImage', models.ImageField(default='', upload_to='media')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
