# Generated by Django 3.2.24 on 2024-04-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userImage',
        ),
    ]
