# Generated by Django 3.2.24 on 2024-04-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_cust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cust',
        ),
    ]
