# Generated by Django 3.2.24 on 2024-04-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_delete_cust'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userInfo',
            new_name='Users',
        ),
    ]
