# Generated by Django 3.2.24 on 2024-04-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_userinfo_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userImage',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
