# Generated by Django 3.2.24 on 2024-04-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_users_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userImage',
        ),
        migrations.AlterField(
            model_name='users',
            name='userEmail',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='users',
            name='userPass',
            field=models.CharField(max_length=61),
        ),
    ]
