# Generated by Django 3.2.24 on 2024-04-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20240414_1130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='TB_Users',
        ),
    ]
