# Generated by Django 3.2.24 on 2024-04-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userId',
            new_name='CustId',
        ),
        migrations.AlterModelTable(
            name='admin',
            table='TB_Admin',
        ),
        migrations.AlterModelTable(
            name='users',
            table='TB_Users',
        ),
    ]
