# Generated by Django 3.2.24 on 2024-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20240415_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userImage',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.FloatField(max_length=55),
        ),
    ]
