# Generated by Django 3.2.24 on 2024-04-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20240415_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userImage',
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(max_length=55),
        ),
    ]
