# Generated by Django 3.2.25 on 2025-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20240415_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userImage',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
