# Generated by Django 3.2.25 on 2025-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_chatpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='user_status',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('visitor', 'Visitor')], default='visitor', max_length=10),
        ),
    ]
