# Generated by Django 3.2.25 on 2025-04-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20250424_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatPair',
        ),
    ]
